package taxi.kassa.view.registration.connection

enum class ImageType {
    YANDEX_D_LICENSE,
    YANDEX_PASSPORT_FIRST,
    YANDEX_PASSPORT_REG,
    YANDEX_STS,
    YANDEX_LICENSE,

    GETT_D_LICENSE,
    GETT_PASSPORT,
    GETT_STS,
    GETT_LICENSE,
    GETT_SELFIE,

    D_LICENSE_FRONT,
    D_LICENSE_BACK,
    PASSPORT_FIRST,
    PASSPORT_REG,
    STS,
    LICENSE_FRONT,
    LICENSE_BACK,
    AUTO_FRONT,
    AUTO_BACK,
    AUTO_LEFT,
    AUTO_RIGHT,
    SELFIE
}