package taxi.kassa.view.registration.connection

enum class ImageType {
    YANDEX_D_LICENSE,
    YANDEX_PASSPORT_FIRST,
    YANDEX_PASSPORT_REG,
    YANDEX_STS,
    YANDEX_LICENSE,

    GETT_D_LICENSE,
    GETT_PASSPORT,
    GETT_STS,
    GETT_LICENSE,
    GETT_SELFIE,

    CITY_D_LICENSE_FRONT,
    CITY_D_LICENSE_BACK,
    CITY_PASSPORT_FIRST,
    CITY_PASSPORT_REG,
    CITY_STS,
    CITY_LICENSE_FRONT,
    CITY_LICENSE_BACK,
    CITY_AUTO_FRONT,
    CITY_AUTO_BACK,
    CITY_AUTO_LEFT,
    CITY_AUTO_RIGHT,
    CITY_SELFIE
}